export enum API {
  CONNECTION = 'connection',
  DISCONNECT = 'disconnect',
  CREATE_PLAYER = 'createPlayer',
  UPDATE_KEYS = 'keys',
  ADD_NEW_PLAYER = 'addPlayer',
  ADD_PLAYERS = 'addPlayers',
  ADD_NEW_BULLET = 'addBullet',
  MOUSE_CLICK = 'mouseClick',
  MOUSE_RIGHT_CLICK = 'mouseRightClick',
  MOUSE_UP = 'mouseUp',
  GET_PLAYERS_STATE = 'getPlayers',
  GET_BULLETS = 'getBullets',
  GET_STATIC_OBJECTS = 'getStaticObjects',
  GET_ITEM_GENERATORS = 'getItemGenerators',
  UPDATE_ITEM_GENERATOR = 'updateItemGenerator',
  DISCONNECT_PLAYER = 'disconnectPlayer',
  WELCOME_NEW_PLAYER = 'helloPlayer',
  UPDATE_DIRECTION = 'updateDirection',
  CREATE_GAME = 'createGame',
  GET_GAMES_LIST = 'getGamesList',
  GET_TEAMS_LIST = 'getTeamsList',
  LEAVE_GAME = 'leaveGame',
  GET_WEAPON_DETAILS = 'getWeaponDetails',
  GET_POWER_DETAILS = 'getPowerDetails',
  UPDATE_TIME_TO_REVIVE = 'updateTimeToRevive',
}
